# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carbohydrates', models.FloatField()),
                ('vitamins', models.FloatField()),
                ('proteins', models.FloatField()),
                ('cholestrol', models.FloatField()),
                ('oils', models.FloatField()),
                ('fats', models.FloatField()),
                ('alcohol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('prep_time', models.DurationField()),
                ('serving', models.IntegerField()),
                ('ingredients', models.ManyToManyField(related_name='FoodItem_recipes', to='recipe.FoodItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
