# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('carbohydrates', 'Carbohydrate'), ('proteins', 'Protein'), ('alcohol', 'Alcohol'), ('fats', 'Fats and Oils'), ('vitamins', 'Vitamin'), ('cholestrols', 'Cholestrol'), ('minerals', 'Mineral')], max_length=25)),
                ('caloric_value_per_gram', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('measurement_unit', models.CharField(max_length=255)),
                ('quantity_per_unit', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_nutrients', to='recipe.FoodCategory')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditem_nutrients', to='recipe.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField()),
                ('prep_time', models.DurationField()),
                ('serving', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituent_recipe', to='recipe.FoodItem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_fooditem', to='recipe.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='FoodItem_recipes', through='recipe.RecipeFoodItem', to='recipe.FoodItem'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Person'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='nutritional_value',
            field=models.ManyToManyField(through='recipe.NutritionalValue', to='recipe.FoodCategory'),
        ),
    ]
