# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('carbohydrates', 'Carbohydrates'), ('proteins', 'Proteins'), ('alcohol', 'Alcohol'), ('fats', 'Fats and Oils')], max_length=25)),
                ('caloric_value_per_gram', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.FoodCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='cholestrol',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='oils',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='proteins',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='vitamins',
        ),
        migrations.AddField(
            model_name='fooditemcategory',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.FoodItem'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.ManyToManyField(through='recipe.FoodItemCategory', to='recipe.FoodCategory'),
        ),
    ]
