# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20160304_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='FoodItem_recipes', through='recipe.RecipeFoodItem', to='recipe.FoodItem'),
        ),
    ]
