# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRoutines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('brief_response', models.TextField()),
                ('detailed_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugarLevelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('before meal', 'Before meal'), ('after meal', 'After meal'), ('fasting glucose', 'Fasting glucose'), ('any', 'Any')], max_length=15)),
                ('sugarLevel', models.CharField(max_length=10)),
                ('diabetic', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Hypoglycemia', 'Hypo'), ('Normal blood sugar level', 'Normal'), ('Hyperglycemia', 'Hyper')], max_length=255)),
                ('explanation', models.CharField(max_length=255)),
                ('remedial_action', models.CharField(max_length=255)),
                ('recommendation', models.CharField(max_length=255)),
            ],
        ),
    ]
