# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_string', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('GE_MSG', 'General messages'), ('VISIT', 'Messages from visit'), ('PATIENT', 'Messages from patients'), ('SYS_MSG', 'System Messages')], default='GE_MSG', max_length=12)),
                ('read', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=20, null=True)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('read',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_string', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('GE_MSG', 'General messages'), ('VISIT', 'Messages from visit'), ('PATIENT', 'Messages from patients'), ('SYS_MSG', 'System Messages')], default='GE_MSG', max_length=12)),
                ('read', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=20, null=True)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('read',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('members', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('response', models.TextField()),
                ('users', models.ManyToManyField(related_name='user_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.UsersGroup'),
        ),
    ]
