# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugarLevelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('before meal', 'Before meal'), ('after meal', 'After meal'), ('fasting glucose', 'Fasting glucose')], max_length=15)),
                ('sugarLevel', models.CharField(max_length=10)),
                ('diabetic', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Hypoglycemia', 'Hypo'), ('Normal blood sugar level', 'Normal'), ('Hyperglycemia', 'Hyper')], max_length=255)),
                ('explanation', models.CharField(max_length=255)),
                ('remedial_action', models.CharField(max_length=255)),
                ('recommendation', models.CharField(max_length=255)),
            ],
        ),
    ]
