# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='detailed_response',
        ),
        migrations.AddField(
            model_name='faqs',
            name='detailed_response_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
