# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20160419_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
