# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('duration', models.DurationField()),
                ('calories_lost', models.CharField(blank=True, max_length=255, null=True)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.ExerciseRoutines')),
            ],
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=255)),
                ('calories_gained', models.DecimalField(decimal_places=3, max_digits=20)),
                ('recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('diabetic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth (YYYY-MM-DD)')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.Gender')),
                ('health_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.HealthDetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SugarLevelsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=255)),
                ('sugar_level', models.DecimalField(decimal_places=3, max_digits=20)),
                ('recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Person')),
            ],
        ),
        migrations.AddField(
            model_name='foodlog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Person'),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Person'),
        ),
    ]
