# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HealthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('abdominal_girth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fasting_glucose', models.DecimalField(decimal_places=4, max_digits=10)),
                ('systole', models.IntegerField()),
                ('diastole', models.IntegerField()),
                ('time_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('diabetic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('other_names', models.CharField(blank=True, max_length=120, null=True)),
                ('date_of_birth', models.DateField(verbose_name='Date of birth (YYYY-MM-DD)')),
            ],
        ),
        migrations.CreateModel(
            name='PersonLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons_set', to='journal.CommunicationLanguage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_language_set', to='journal.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image/png', 'PNG'), ('image/jpeg', 'JPEG')], max_length=100)),
                ('data', models.FileField(upload_to=journal.models.get_directory)),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.IntegerField(help_text='The size of the attachment in bytes')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='communication_language',
            field=models.ManyToManyField(through='journal.PersonLanguage', to='journal.CommunicationLanguage'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.Gender'),
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.MaritalStatus'),
        ),
        migrations.AddField(
            model_name='healthdetails',
            name='medication',
            field=models.ManyToManyField(related_name='medication_users', to='journal.Medication'),
        ),
        migrations.AddField(
            model_name='healthdetails',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_healthdetails', to='journal.Person'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.ContactType'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.Person'),
        ),
    ]
