# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedfoodlog',
            name='period',
            field=models.CharField(default='bf', max_length=255),
            preserve_default=False,
        ),
    ]
