# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_sugarleveldetails'),
        ('recipe', '0002_auto_20160408_2013'),
        ('journal', '0002_auto_20160410_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedExerciseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('calories_lost', models.CharField(blank=True, max_length=255, null=True)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_details_persons', to='community.ExerciseRoutines')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_log_details', to='journal.Person')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedFoodLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('calories_gained', models.DecimalField(decimal_places=3, max_digits=20)),
                ('recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_persons', to='recipe.Recipe')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_log_details', to='journal.Person')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedSugarLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugarDetails_log', to='community.SugarLevelDetails')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugar_log_details', to='journal.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='person',
        ),
        migrations.RemoveField(
            model_name='foodlog',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodlog',
            name='person',
        ),
        migrations.RemoveField(
            model_name='sugarlevelslog',
            name='person',
        ),
        migrations.DeleteModel(
            name='ExerciseLog',
        ),
        migrations.DeleteModel(
            name='FoodLog',
        ),
        migrations.DeleteModel(
            name='SugarLevelsLog',
        ),
        migrations.AddField(
            model_name='person',
            name='exercise_logs',
            field=models.ManyToManyField(through='journal.DetailedExerciseLog', to='community.ExerciseRoutines'),
        ),
        migrations.AddField(
            model_name='person',
            name='food_logs',
            field=models.ManyToManyField(through='journal.DetailedFoodLog', to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='person',
            name='sugar_logs',
            field=models.ManyToManyField(through='journal.DetailedSugarLog', to='community.SugarLevelDetails'),
        ),
    ]
