# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_detailedfoodlog_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdetails',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
