# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160429_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedfoodlog',
            name='cholesterol_gained',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
